version: '3'
services:
  portfolio:
    build:
      context: ./portfolio
    volumes:
      - ./portfolio:/usr/src/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - frontend
    ports:
        - 3000:3000
  nginx:
    image: linuxserver/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/letsencrypt:/config
    networks:
      - frontend
    container_name: nginx
    environment:
      - PUID=1001 # get on dockerhost through command "id <user>""
      - PGID=1001
      - EMAIL=thealbertyang@gmail.com
      - URL=thealbertyang.com
      - SUBDOMAINS=www
      - TZ=America/NewYork
      - VALIDATION=dns # using dns validation
      - DNSPLUGIN=digitalocean # via dnsimple, note there is additional configuration require separate from this file
      # - STAGING=true # this should be uncommented when testing for initial success, to avoid some rate limiting
    depends_on:
      - portfolio
networks:
  frontend:
    external: false
